/* panel/oneg4panellimits.h
 * Main panel implementation, window management
 */

#ifndef ONEG4PANELLIMITS_H
#define ONEG4PANELLIMITS_H

#define PANEL_DEFAULT_SIZE 32
#define PANEL_MINIMUM_SIZE 16
#define PANEL_MAXIMUM_SIZE 200
#define PANEL_HIDE_SIZE 4

#define PANEL_DEFAULT_ICON_SIZE 22
#define PANEL_DEFAULT_LINE_COUNT 1

#define PANEL_DEFAULT_BACKGROUND_COLOR "#CCCCCC"

#define PANEL_HIDE_DELAY 500
#define PANEL_HIDE_FIRST_TIME (5000 - PANEL_HIDE_DELAY)

#define PANEL_SHOW_DELAY 0

#define SETTINGS_SAVE_DELAY 3000
#endif  // ONEG4PANELLIMITS_H